apiVersion: v1            
kind: ResourceQuota       
metadata:                 
  name: quota
  namespace: data-namespace         
spec:                     
  hard:                   
    limits.cpu: 500m      
    limits.memory: 256Mi  
    requests.cpu: 250m    
    requests.memory: 128Mi
                          
---                     

apiVersion: v1                
kind: LimitRange        
metadata:               
  name: quota
  namespace: data-namespace       
spec:                   
  limits:               
    - type: "Container" 
      defaultRequest:   
        cpu: 50m        
        memory: 32Mi    
      default:          
        cpu: 100m       
        memory: 64Mi