apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sysops
  namespace: data-namespace
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"] 

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sysops-global
subjects:
- kind: User
  name: sysops-role
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: sysops
  apiGroup: rbac.authorization.k8s.io