apiVersion: kubedb.com/v1beta
kind: Snapshot
metadata:
  name: azure-snapshot
  namespace: data-namespace
  labels:
    kubedb.com/kind: Postgres  
spec:
  databaseName: k8sbackupstorage
  storageSecretName: azure-secret
  azure:
    container: backup-container
    prefix: backup